permalink: /:year/:month/:day/:title.html	#博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
	name: dongkuo
	email: 893309018@qq.com
	link: http://dongkuo.github.io/
title: dongkuo的博客                        #自定义常量
locals:                                     #自定义常量
	tags: 标签
	about: 关于
	active: 技术                            #自定义常量
markdown: redcarpet                         #markdown解释器