# Site settings
title: 学数学的程序猿
email: 893309018@qq.com
description: 
baseurl: ""
url: "http://yourdomain.com"
github_username: dongkuo
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: Kramdown
kramdown:
    input: GFM

subtitle: 不学数学的程序员不是好的段子手
favicon: /images/avatar.jpg